# My first work

In [2]:
# The code was removed by Watson Studio for sharing.

ParserError: Error tokenizing data. C error: Expected 1 fields in line 14, saw 2

In [3]:

body = client_71e9c320a06d4cc293985a491de49be8.get_object(Bucket='projectwork2-donotdelete-pr-y3d86le6dk5i2t',Key='weather-stations20140101-20141231.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_2 = pd.read_csv(body)
df_data_2.head()

,Stn_Name,Lat,Long,Prov,Tm,DwTm,D,Tx,DwTx,Tn,...,DwP,P%N,S_G,Pd,BS,DwBS,BS%,HDD,CDD,Stn_No
0,CHEMAINUS,48.935,-123.742,BC,8.2,0.0,NaN,13.5,0.0,1.0,...,0.0,NaN,0.0,12.0,NaN,NaN,NaN,273.3,0.0,1011500
1,COWICHAN LAKE FORESTRY,48.824,-124.133,BC,7.0,0.0,3.0,15.0,0.0,-3.0,...,0.0,104.0,0.0,12.0,NaN,NaN,NaN,307.0,0.0,1012040
2,LAKE COWICHAN,48.829,-124.052,BC,6.8,13.0,2.8,16.0,9.0,-2.5,...,9.0,NaN,NaN,11.0,NaN,NaN,NaN,168.1,0.0,1012055
3,DISCOVERY ISLAND,48.425,-123.226,BC,NaN,NaN,NaN,12.5,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1012475
4,DUNCAN KELVIN CREEK,48.735,-123.728,BC,7.7,2.0,3.4,14.5,2.0,-1.0,...,2.0,NaN,NaN,11.0,NaN,NaN,NaN,267.7,0.0,1012573

In [4]:

body = client_71e9c320a06d4cc293985a491de49be8.get_object(Bucket='projectwork2-donotdelete-pr-y3d86le6dk5i2t',Key='data.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

df_data_3 = pd.read_csv(body)
df_data_3.head()

,Claim_Period,Program_Closure_Flag,Report_Data_Status,Super_License_Flag,ProgramTypeName_Value,NonProfitFlagDesc_Value,PhysicalAddressLine2_Value,Program_Activity_Start_Date,Program_Activity_End_Date,License_Issue_Date,...,PhysicalPostalCode_Value,ContactLastName_Value,ContactFirstName_Value,ContactTitle_Value,ContactPhoneNumber_Value,CaseworkerSurname_Value,CaseworkerFirstname_Value,AccreditationStatusDesc_Value,Mapping_Coordinate_LATITUDE,Mapping_Coordinate_LONGITUDE
0,202009,Open,Partial,Y,DAY CARE PROGRAM,For Profit,Not Available,09/25/2020,01/31/2021,02/01/2018,...,T3A0C6,LAMONT,STEPHANIE,OWNER,4037021488,BENARD-SAMPSON,NATHALIE,Not Accredited,51.084481,-114.150418
1,202009,Open,Partial,Y,OUT OF SCHOOL CARE PROGRAM,For Profit,Not Available,09/24/2020,04/19/2022,04/20/2019,...,T6J3S3,DJERMAN,SONJA/RANKO,DIRECTORS,7809647280,DELL,PEARL,Not Accredited,53.455028,-113.531746
2,202009,Open,Partial,N,OUT OF SCHOOL CARE PROGRAM,For Profit,Not Available,09/21/2020,09/01/2021,09/21/2020,...,T9H4V3,NELSON,GIFTY,OWNER,7808806510,OVERBECK,TAMI,Accredited,56.727135,-111.449229
3,202009,Open,Partial,Y,DAY CARE PROGRAM,For Profit,Not Available,09/16/2020,09/15/2023,09/16/2020,...,T2X4A7,AFONYA,ANI,OPERATOR,4036126361,KELLY,HEATHER,Not Accredited,50.862368,-114.009321
4,202009,Open,Partial,Y,DAY CARE PROGRAM,For Profit,Not Available,09/15/2020,09/14/2023,09/15/2020,...,T2Y4X1,ZHANG,YAN MEI,OPERATOR,4036903720,FREMPONG,AUGUSTINA,Not Accredited,50.913915,-114.122602

In [6]:
a=2